/*
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: oroca_bldc.xml

Note: this file has been auto-generated. DO NOT EDIT
*/

using System;

    
using System.Reflection;    
    
[assembly: AssemblyTitle("Mavlink Classes")]
[assembly: AssemblyDescription("Generated Message Classes for Mavlink. See http://qgroundcontrol.org/mavlink/start")]
[assembly: AssemblyProduct("Mavlink")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

    namespace MavLink
{

}

    
   
namespace MavLink
{

    public abstract class MavlinkMessage
    {
        public abstract int Serialize(byte[] bytes, ref int offset);
    }

	/// <summary>
	/// Message For set angular velocity
	/// </summary>
	public class Msg_set_velocity : MavlinkMessage
    {

		/// <summary>
		/// velocity value
		/// </summary>
		public UInt16 ref_angular_velocity;

        public override int Serialize(byte[] bytes, ref int offset)
            {
                return MavLinkSerializer.Serialize_SET_VELOCITY(this, bytes, ref offset);
            }        
	}


	/// <summary>
	/// debug String
	/// </summary>
	public class Msg_debug_string : MavlinkMessage
    {

		/// <summary>
		/// string
		/// </summary>
		public byte[] dbg_str; // Array size 250

        public override int Serialize(byte[] bytes, ref int offset)
            {
                return MavLinkSerializer.Serialize_DEBUG_STRING(this, bytes, ref offset);
            }        
	}

}

